name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: 16.x

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install Yarn packages
        run: yarn install --immutable --immutable-cache --check-cache
      
      - name: Get package version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "::set-output name=version::$VERSION"
      
      - name: 'npm: Build All'
        run: npm run build:all
      
      # Dist locations in: dist/Mac, dist/Windows, dist/Windows_Tray, dist/Linux
      # Upload artifacts
      - name: Upload Windows build
        uses: actions/upload-artifact@v2
        with:
          name: android-messages-windows_v${{ steps.version.outputs.version }}.zip
          path: dist/Windows/Google Messages-win32-x64/*
      - name: Upload Windows_Tray build
        uses: actions/upload-artifact@v2
        with:
          name: android-messages-windows-tray_v${{ steps.version.outputs.version }}.zip
          path: dist/Windows_Tray/Google Messages-win32-x64/*
      
